### PR TITLE
fix docker support

### PR DESCRIPTION
**Pull request by darwin**

### CODE REVIEW

**Comment by darwin** [comment]
@bitromortac feel free to ping me when docker support breaks again, I will jump on it. I just don't actively watch this repo for changes.

**Comment by bitromortac** [comment]
Thank you very much for the contribution! I'm sorry I had to break the docker functionality and didn't have time to fix it. Thank you also for the offer, will definitely come back to you :).

I tried to build the image, but it seems there are issues with the different versions of the python environments. In the first part of the Dockerfile I'm getting version 3.8 and in the second 3.7.3.
The build stops with
```
Step 18/20 : RUN pip install -r requirements.txt
 ---> Running in 92adff95951f
Traceback (most recent call last):
  File "/root/.venv/bin/pip", line 6, in <module>
    from pip._internal import main
ModuleNotFoundError: No module named 'pip'
```
Could be related to this https://github.com/pypa/pip/issues/5373 . Will get back to this later.

**Comment by darwin** [comment]
Well, I have just tested it here and it seems to work.

Could you try to run as `./build.sh --no-cache`. I wonder if you have some ancient version for `python:3-slim` in your docker caches.

Anyways, I'm going to add a commit which will replace python:3-slim everywhere.

**Comment by bitromortac** [comment]
Replacing python:3-slim with python:3 worked, thanks again!

**Pull request merged**
