### PR TITLE
Add Dockerfile with test requirements

### PR DESCRIPTION
**Pull request by 3nprob**
Depends on `lndmanage:local` from https://github.com/bitromortac/lnregtest/pull/7

### CODE REVIEW

**Comment by 3nprob** [comment]
I am getting one failed test on current master - is that the case for you as well when you run in your environment @bitromortac ?

```
======================================================================
ERROR: test_circle (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_circle
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/root/lndmanage/test/test_circle.py", line 9, in <module>
    from lndmanage.lib.listings import ListChannels
  File "/root/lndmanage/lndmanage/lib/listings.py", line 14, in <module>
    from lndmanage.lib.forwardings import (
  File "/root/lndmanage/lndmanage/lib/forwardings.py", line 9, in <module>
    from lndmanage.lib.node import LndNode
  File "/root/lndmanage/lndmanage/lib/node.py", line 21, in <module>
    from lndmanage.lib.network import Network
  File "/root/lndmanage/lndmanage/lib/network.py", line 11, in <module>
    from lndmanage.lib.rating import ChannelRater
  File "/root/lndmanage/lndmanage/lib/rating.py", line 4, in <module>
    from lndmanage import settings
  File "/root/lndmanage/lndmanage/settings.py", line 121, in <module>
    set_lndmanage_home_dir()
  File "/root/lndmanage/lndmanage/settings.py", line 72, in set_lndmanage_home_dir
    check_or_create_configuration(home_dir)
  File "/root/lndmanage/lndmanage/lib/configure.py", line 76, in check_or_create_configuration
    exit(0)
  File "/usr/local/lib/python3.10/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0


======================================================================
FAIL: test_liquidity_hints (test_pathfinding.TestGraph)
3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/lndmanage/test/test_pathfinding.py", line 100, in test_liquidity_hints
    self.assertEqual(['A', 'D', 'E'], path)
AssertionError: Lists differ: ['A', 'D', 'E'] != ['A', 'B', 'E']

First differing element 1:
'D'
'B'

- ['A', 'D', 'E']
?        ^

+ ['A', 'B', 'E']
?        ^


----------------------------------------------------------------------
Ran 25 tests in 497.259s

FAILED (failures=1, errors=1)
```

**Comment by 3nprob** [comment]
`ImportError: Failed to import test module: test_circle` seems to be because the test runner ` seems to be because just importing  `lndmanage.settings` will trigger attempting to use the default homedir, before it can be overriden.
https://github.com/bitromortac/lndmanage/blob/2dc2fae8f8b6ac0dfaf7c861d3f5b074b86e0006/lndmanage/settings.py#L121 

The `test_liquidity_hints` test failure seems to be something else

**Comment by 3nprob** [comment]
Added a kind of dirty fix reordering imports and setting default value for `LNDMANAGE_HOME`, which fixes the import error.

Remaining failure on run now:

```
======================================================================
FAIL: test_liquidity_hints (test_pathfinding.TestGraph)
3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/lndmanage/test/test_pathfinding.py", line 102, in test_liquidity_hints
    self.assertEqual(['A', 'D', 'E'], path)
AssertionError: Lists differ: ['A', 'D', 'E'] != ['A', 'B', 'E']

First differing element 1:
'D'
'B'

- ['A', 'D', 'E']
?        ^

+ ['A', 'B', 'E']
?        ^


----------------------------------------------------------------------
Ran 27 tests in 630.117s

FAILED (failures=1)

```

**Comment by bitromortac** [comment]
Cool you decided to work on that. I know that one or two tests are flaky (didn't have yet time to go after it in detail), try to run them in isolation. Going to revive #84 soon, so tests could change a bit. Perhaps it would make sense to hold this back a bit.

**Comment by bitromortac** [comment]
Ok, I pushed some raw code of how the new async tests could look like in #84. I described a bit what I'm trying to do there, feedback is welcome :slightly_smiling_face:

**Comment by 3nprob** [comment]
>  try to run them in isolation

How do I indicate which tests to run individually? I'm new to this way of testing Python and got errors doing it my naive way

**Comment by 3nprob** [comment]
> Cool you decided to work on that. I know that one or two tests are flaky (didn't have yet time to go after it in detail), try to run them in isolation. Going to revive #84 soon, so tests could change a bit. Perhaps it would make sense to hold this back a bit.

Got it. #84 still seems to have the issue with the test suite attempting to use/initiate a production config that I fixed in d60504dccb5114671686df674b9c19091a3b991e - would be nice if that can be resolved separately.

(I'd also argue that #84 is quite big already and touches many parts and functions - making the tests run reliably separately before that, and any test overhaul not directly tied to the changes in it, would be ideal, to have higher confidence that existing functionality does not break. This includes the making-tests-async-changes. In general it's good idea to split things like that up IMO. Left a separate comment on that there as well!)

**Comment by 3nprob** [comment]
Addressed the failing tests in #129 (should be independent of all currently open PRs)

**Comment by 3nprob** [comment]
Superseded by #128

**Pull request closed without merging**
