### PR TITLE
Automatic docker builds

### PR DESCRIPTION
**Pull request by kroese**
I created workflows that use Github Actions to automaticly build and publish the container to DockerHub and GHCR.io, and added the related badges to the README.

### CODE REVIEW

**Comment by bitromortac** [comment]
Hey, thank you very much for this work and sorry for not getting back to you for this earlier. My original goal was to reduce the number of sites where lndmanage is hosted and to have only a single source of truth (see also https://github.com/bitromortac/lndmanage/releases/tag/v0.15.0).
Since lndmanage deals with admin macaroons, I would like to reduce the number of ways bad distributions could sneak into the process as much as possible, which is why I plan to remove lndmanage from pipy and switch over to a github-based pip install, e.g. `python -m pip install 'lndmanage @ git+https://github.com/bitromortac/lndmanage'`.
If an automatic docker-based image creation is added, how could one verify that its contents are consistent with the git repo's? I understand that this would ease deployment, but security is my main concern here.

**Comment by kroese** [comment]
In the Actions tab there is the log for every build, which can be used for this purpose. And maybe you could add this: https://github.com/dlorenc/verifyme It makes  Github Actions verifyable. 

But Im not sure if this is an issue in the first place. It's being build on Github servers, by Github themselves, and its Github pulling the sourcecode. There is no way for a thirdparty to interfere with that. And if people don't trust Github, they can just build the image themselves. But then they still must trust Github to give them the correct sourcecode, so it really doesnt change anything.

Nobody has to use these prebuild images, it's only a service for people who want them. I also use prebuild images for BTC and LND, so why not for managelnd?

**Comment by kroese** [comment]
I still don't really understand your objection to this? 

It runs as a Github Action, so the source is pulled by Github themselves during the workflow run. I really cannot think of any security risk that would introduce.

**Comment by bitromortac** [comment]
Right now it's uploaded to your account in dockerhub, which means you could upload an image that you built using different source code, is that correct? An alternative to give you more convenience would be to maintain your own fork of lndmanage merging in latest changes from the main repo via github. This way you should get automatic builds as well.

**Comment by kroese** [comment]
@bitromortac No, it's uploaded to the account specified in the repository secret DOCKERHUB_USERNAME. And in my forked repository I pointed this secret to my own account just for testing. 

But if you merged this pull request it will not include those secret variables, so you need to create two secrets called  DOCKERHUB_USERNAME and DOCKERHUB_TOKEN which point to your own account.

Screenshot_20230511_103155_Samsung Internet
Screenshot_20230511_103233_Samsung Internet

In the README I needed to hardcode my username for the badges (because variables are not supported there), so you will need to replace any instances of "kroese" with "bitromortac" there.

EDIT: Or do you mean that people would have to trust you to not replace the images that were uploaded by the Github Action? In that case they could compare the date/time of the image upload to the date/time when the Github action was executed. Or they could compare the hash from the action log, to the hash on Dockerhub. But also when they build from source, they need to trust you that you didn't put any backdoors in the source, so it really doesn't change anything.

**Pull request closed without merging**
